### ISSUE TITLE
Crash when trying to run r251-2 Stable on Win7

### ISSUE THREAD

**Issue by Alaadel** [TheRealDannyyy/Construct-3-Desktop-Launcher#94]
**Describe the bug**
I downloaded the launcher (amazing tool, by the way!) and installed a custom release 251-2 Stable. I launched it and made a game and all was fine.
I restarted my system and tried to launch 251-2, but it always crashes at the start (crashes the launcher with it too). Tried to open C3 and the launcher as admin, and tried to run C3 from the folder directly, but always the same result: crash at the start (only once I caught a glimpse of the editor window show and crash, but all the other times it didn't even appear on screen).

I installed 251 and it worked fine for now. I will update this post if anything new happens!

Thanks.

**Comment by DannyyyOnGit** [comment]
> **Describe the bug** I downloaded the launcher (amazing tool, by the way!) and installed a custom release 251-2 Stable. I launched it and made a game and all was fine. I restarted my system and tried to launch 251-2, but it always crashes at the start (crashes the launcher with it too). Tried to open C3 and the launcher as admin, and tried to run C3 from the folder directly, but always the same result: crash at the start (only once I caught a glimpse of the editor window show and crash, but all the other times it didn't even appear on screen).
> 
> I installed 251 and it worked fine for now. I will update this post if anything new happens!
> 
> Thanks.

This can happen sometimes. It's odd that the launcher itself would crash as well.
Support for this project has ended so I might not provide and help in the future.

_Thanks for using my piece of software!_
